"""
Backends: the library, lowered into things you can run.

Five artifacts, one source:

    python     a plain module + a pytest file built from the #examples
    notebook   one .ipynb per def — the maths, the citation, the code, a sweep
    rust       a std-only crate: pure functions, a JSON HTTP backend, tests
    nextjs     a TS lib, an API route per def, and a page that calls them
    lean       real Lean 4, for when the toolchain is installed to check it

Everything under out/ is an artifact. It is regenerable, it carries a
"do not edit" header, and `check.drift()` will tell you if someone edited it
anyway. The library is the source of truth; these are its shadows.
"""
from __future__ import annotations

import json

from .. import ir
from ..ir import Def
from . import emit
from .emit import TARGETS, Target, function

BANNER = 'generated by leanland — edit lib/*.lean and regenerate, not this file'


def order(defs: dict[str, Def]) -> list[Def]:
    """Definition order: callee before caller."""
    out, seen = [], set()

    def visit(name, stack=()):
        if name in seen or name not in defs:
            return
        if name in stack:
            raise ValueError(f'circular dependency: {" -> ".join(stack + (name,))}')
        for dep in defs[name].deps:
            visit(dep, stack + (name,))
        seen.add(name)
        out.append(defs[name])

    for n in defs:
        visit(n)
    return out


def closure(defs: dict[str, Def], names) -> dict[str, Def]:
    """A def and everything it transitively calls — what has to travel with it."""
    out: dict[str, Def] = {}

    def visit(n):
        if n in out or n not in defs:
            return
        out[n] = defs[n]
        for dep in defs[n].deps:
            visit(dep)

    for n in names:
        visit(n)
    return out


def _value(v, t: str, tgt: Target) -> str:
    if t.startswith('Vec '):
        return tgt.vec([_value(x, ir.elem(t), tgt) for x in v], t)
    return tgt.lit(v, t)


def cases(d: Def, defs: dict[str, Def]) -> list[dict]:
    """Resolve a def's #examples to concrete values (the paper's own numbers)."""
    out = []
    for ex in d.examples:
        args = [ir.evaluate(a, {}, defs) for a in ex['args']]
        out.append({'args': args, 'expect': ir.evaluate(ex['expect'], {}, defs),
                    'tol': ex['tol']})
    return out


# ---------------------------------------------------------------------------
# python
# ---------------------------------------------------------------------------

def python(defs: dict[str, Def]) -> str:
    tgt = TARGETS['py']
    body = [function(d, defs, tgt) for d in order(defs)]
    return f'"""{BANNER}"""\nimport math\n\n\n' + '\n\n\n'.join(body) + '\n'


def python_tests(defs: dict[str, Def], mod: str = 'leanland_lib') -> str:
    tgt = TARGETS['py']
    out = [f'"""{BANNER}\n\nEvery case here is a number the source paper states."""',
           'import math', f'from {mod} import *', '']
    n = 0
    for d in order(defs):
        for c in cases(d, defs):
            args = ', '.join(_value(v, t, tgt) for v, (_, t) in zip(c['args'], d.params))
            exp = _value(c['expect'], d.ret, tgt)
            out.append(f'def test_{d.name}_{n}():')
            src = d.source.get('key', 'unsourced')
            out.append(f'    # {src}')
            if d.ret == 'Bool':
                out.append(f'    assert {d.name}({args}) is {exp}')
            else:
                out.append(f'    assert math.isclose({d.name}({args}), {exp}, '
                           f'rel_tol=0, abs_tol={c["tol"]!r})')
            out.append('')
            n += 1
    if n == 0:
        out.append('def test_no_examples():\n'
                   '    raise AssertionError("the library states no #examples to check")\n')
    return '\n'.join(out)


# ---------------------------------------------------------------------------
# typescript / next.js
# ---------------------------------------------------------------------------

def typescript(defs: dict[str, Def]) -> str:
    tgt = TARGETS['ts']
    body = [function(d, defs, tgt) for d in order(defs)]
    return f'// {BANNER}\n\n' + '\n\n'.join(body) + '\n'


def ts_registry(defs: dict[str, Def]) -> str:
    """A name -> {fn, params} table so one API route serves every def."""
    rows = []
    for d in order(defs):
        ps = ', '.join(json.dumps({'name': n, 'type': t}) for n, t in d.params)
        rows.append(f"  {d.name}: {{ fn: F.{d.name} as (...a: any[]) => any, "
                    f"ret: {json.dumps(d.ret)}, doc: {json.dumps(d.doc)}, "
                    f"source: {json.dumps(d.source)}, params: [{ps}] }},")
    return (f'// {BANNER}\nimport * as F from "./leanland";\n\n'
            'export type Param = { name: string; type: string };\n'
            'export const LIBRARY: Record<string, { fn: (...a: any[]) => any; ret: string;'
            ' doc: string; source: Record<string, string>; params: Param[] }> = {\n'
            + '\n'.join(rows) + '\n};\n\nexport const NAMES = Object.keys(LIBRARY);\n')


ROUTE_TS = '''// {banner}
import {{ NextRequest, NextResponse }} from "next/server";
import {{ LIBRARY }} from "@/lib/leanland.registry";

// One route for the whole library: a def is data here, not a hand-written
// endpoint, so adding a formula to lib/*.lean adds an endpoint and nothing else.
export async function POST(req: NextRequest, ctx: {{ params: Promise<{{ fn: string }}> }}) {{
  const {{ fn }} = await ctx.params;
  const entry = LIBRARY[fn];
  if (!entry) return NextResponse.json({{ error: `unknown def '${{fn}}'` }}, {{ status: 404 }});
  const body = await req.json().catch(() => ({{}}));
  const args = entry.params.map((p) => (body as any)[p.name]);
  const missing = entry.params.filter((p, i) => args[i] === undefined).map((p) => p.name);
  if (missing.length) {{
    return NextResponse.json({{ error: `missing: ${{missing.join(", ")}}` }}, {{ status: 400 }});
  }}
  try {{
    return NextResponse.json({{ fn, args, value: entry.fn(...args), source: entry.source }});
  }} catch (e: any) {{
    return NextResponse.json({{ error: String(e?.message ?? e) }}, {{ status: 500 }});
  }}
}}

export async function GET(_req: NextRequest, ctx: {{ params: Promise<{{ fn: string }}> }}) {{
  const {{ fn }} = await ctx.params;
  const entry = LIBRARY[fn];
  if (!entry) return NextResponse.json({{ error: `unknown def '${{fn}}'` }}, {{ status: 404 }});
  const {{ fn: _f, ...meta }} = entry as any;
  return NextResponse.json({{ name: fn, ...meta }});
}}
'''

PAGE_TSX = '''// {banner}
"use client";
import {{ useState }} from "react";
import {{ LIBRARY, NAMES }} from "@/lib/leanland.registry";

export default function LeanlandPage() {{
  const [name, setName] = useState(NAMES[0]);
  const [vals, setVals] = useState<Record<string, string>>({{}});
  const [out, setOut] = useState<string>("");
  const def = LIBRARY[name];

  async function run() {{
    const body: Record<string, unknown> = {{}};
    for (const p of def.params) {{
      const raw = vals[`${{name}}.${{p.name}}`] ?? "";
      body[p.name] = p.type.startsWith("Vec")
        ? raw.split(/[,\\s]+/).filter(Boolean).map(Number)
        : p.type === "Bool" ? raw === "true" : Number(raw);
    }}
    const r = await fetch(`/api/leanland/${{name}}`, {{
      method: "POST", headers: {{ "content-type": "application/json" }},
      body: JSON.stringify(body),
    }});
    setOut(JSON.stringify(await r.json(), null, 2));
  }}

  return (
    <main style={{{{ fontFamily: "ui-monospace, monospace", padding: 24, maxWidth: 720 }}}}>
      <h1>leanland</h1>
      <p style={{{{ opacity: 0.7 }}}}>{{NAMES.length}} definitions, lowered from lib/*.lean</p>
      <select value={{name}} onChange={{(e) => {{ setName(e.target.value); setOut(""); }}}}>
        {{NAMES.map((n) => <option key={{n}} value={{n}}>{{n}}</option>)}}
      </select>
      <p>{{def.doc}} {{def.source?.key ? <em>({{def.source.key}})</em> : null}}</p>
      {{def.params.map((p) => (
        <div key={{p.name}} style={{{{ margin: "6px 0" }}}}>
          <label>{{p.name}} : {{p.type}}{{" "}}
            <input
              value={{vals[`${{name}}.${{p.name}}`] ?? ""}}
              onChange={{(e) => setVals({{ ...vals, [`${{name}}.${{p.name}}`]: e.target.value }})}}
            />
          </label>
        </div>
      ))}}
      <button onClick={{run}}>evaluate</button>
      <pre>{{out}}</pre>
    </main>
  );
}}
'''


def nextjs(defs: dict[str, Def]) -> dict[str, str]:
    """A drop-in Next.js app-router tree. Copy `lib/` and `app/` into any Next
    project, or run this folder on its own."""
    return {
        'lib/leanland.ts': typescript(defs),
        'lib/leanland.registry.ts': ts_registry(defs),
        'app/api/leanland/[fn]/route.ts': ROUTE_TS.format(banner=BANNER),
        'app/leanland/page.tsx': PAGE_TSX.format(banner=BANNER),
        'package.json': json.dumps({
            'name': 'leanland-app', 'private': True, 'version': '0.1.0',
            'scripts': {'dev': 'next dev', 'build': 'next build', 'start': 'next start'},
            'dependencies': {'next': '^15.0.0', 'react': '^19.0.0', 'react-dom': '^19.0.0'},
            'devDependencies': {'typescript': '^5.6.0', '@types/react': '^19.0.0',
                                '@types/node': '^22.0.0'},
        }, indent=2) + '\n',
        'tsconfig.json': json.dumps({
            'compilerOptions': {
                'target': 'ES2020', 'lib': ['dom', 'ES2020'], 'strict': True,
                'jsx': 'preserve', 'module': 'esnext', 'moduleResolution': 'bundler',
                'esModuleInterop': True, 'skipLibCheck': True, 'noEmit': True,
                'paths': {'@/*': ['./*']},
            },
            'include': ['**/*.ts', '**/*.tsx', 'next-env.d.ts'],
        }, indent=2) + '\n',
        'next.config.mjs': '/** @type {import("next").NextConfig} */\nexport default {};\n',
        'README.md': f'# leanland — generated Next.js surface\n\n{BANNER}\n\n'
                     '`/leanland` is a page with one form per definition; '
                     '`/api/leanland/<name>` evaluates one (POST with the parameters '
                     'as JSON, GET for its signature and citation).\n',
    }


# ---------------------------------------------------------------------------
# rust
# ---------------------------------------------------------------------------

def rust(defs: dict[str, Def]) -> str:
    tgt = TARGETS['rs']
    body = [function(d, defs, tgt) for d in order(defs)]
    return (f'//! {BANNER}\n#![allow(clippy::all, unused_parens, dead_code)]\n\n'
            + '\n\n'.join(body) + '\n')


def rust_tests(defs: dict[str, Def]) -> str:
    tgt = TARGETS['rs']
    out = [f'//! {BANNER}', 'use leanland::*;', '']
    n = 0
    for d in order(defs):
        for c in cases(d, defs):
            args = ', '.join(_value(v, t, tgt) for v, (_, t) in zip(c['args'], d.params))
            exp = _value(c['expect'], d.ret, tgt)
            out.append('#[test]')
            out.append(f'fn {d.name}_{n}() {{')
            if d.ret == 'Bool':
                out.append(f'    assert_eq!({d.name}({args}), {exp});')
            else:
                out.append(f'    let got = {d.name}({args}) as f64;')
                out.append(f'    assert!((got - ({exp}) as f64).abs() <= {c["tol"]!r}, '
                           f'"{d.name}: {{}}", got);')
            out.append('}')
            out.append('')
            n += 1
    return '\n'.join(out)


def rust_server(defs: dict[str, Def]) -> str:
    """A std-only JSON backend: no crates, so it builds on a box with no network
    and there is no dependency tree between a formula and serving it. Swap in
    axum by rewriting this file and adding two lines to Cargo.toml."""
    arms = []
    for d in order(defs):
        gets = []
        for i, (n, t) in enumerate(d.params):
            if t.startswith('Vec '):
                gets.append(f'            let {n} = field_vec(&body, "{n}")?;')
            elif t == 'Bool':
                gets.append(f'            let {n} = field_num(&body, "{n}")? != 0.0;')
            elif t in ('Int', 'Nat'):
                gets.append(f'            let {n} = field_num(&body, "{n}")? as i64;')
            else:
                gets.append(f'            let {n} = field_num(&body, "{n}")?;')
        call_args = ', '.join(('&' + n) if t.startswith('Vec ') else n for n, t in d.params)
        body_lines = '\n'.join(gets)
        ret = f'lib::{d.name}({call_args})'
        conv = 'if v { 1.0 } else { 0.0 }' if d.ret == 'Bool' else 'v as f64'
        arms.append(f'        "{d.name}" => {{\n{body_lines}\n'
                    f'            let v = {ret};\n'
                    f'            Ok(format!("{{{{\\"fn\\":\\"{d.name}\\",\\"value\\":{{}}}}}}", '
                    f'{{ let v = {conv}; v }}))\n        }}')
    sigs = ', '.join(
        '{{\\"name\\":\\"%s\\",\\"ret\\":\\"%s\\",\\"params\\":[%s]}}' % (
            d.name, d.ret,
            ','.join('{{\\"name\\":\\"%s\\",\\"type\\":\\"%s\\"}}' % (n, t) for n, t in d.params))
        for d in order(defs))
    return RUST_MAIN.format(banner=BANNER, arms='\n'.join(arms), sigs=sigs)


RUST_MAIN = r'''//! {banner}
//!
//! POST /<def>  {{"param": value, ...}}  ->  {{"fn": "...", "value": ...}}
//! GET  /       the library's signatures
//!
//! std only — no crates, so `cargo build` works offline and nothing sits
//! between a definition and its endpoint.
use std::io::{{BufRead, BufReader, Read, Write}};
use std::net::{{TcpListener, TcpStream}};

use leanland as lib;   // the same crate's library target — one copy of the maths

fn field<'a>(body: &'a str, key: &str) -> Option<&'a str> {{
    let pat = format!("\"{{}}\"", key);
    let i = body.find(&pat)? + pat.len();
    let rest = &body[i..];
    let j = rest.find(':')? + 1;
    Some(rest[j..].trim_start())
}}

fn field_num(body: &str, key: &str) -> Result<f64, String> {{
    let s = field(body, key).ok_or_else(|| format!("missing {{}}", key))?;
    let end = s.find(|c: char| !(c.is_ascii_digit() || "+-.eE".contains(c))).unwrap_or(s.len());
    s[..end].parse::<f64>().map_err(|_| format!("bad number for {{}}", key))
}}

fn field_vec(body: &str, key: &str) -> Result<Vec<f64>, String> {{
    let s = field(body, key).ok_or_else(|| format!("missing {{}}", key))?;
    let s = s.strip_prefix('[').ok_or_else(|| format!("{{}} must be an array", key))?;
    let end = s.find(']').ok_or_else(|| format!("{{}} must be an array", key))?;
    s[..end].split(',').map(|p| p.trim()).filter(|p| !p.is_empty())
        .map(|p| p.parse::<f64>().map_err(|_| format!("bad number in {{}}", key)))
        .collect()
}}

fn dispatch(name: &str, body: &str) -> Result<String, String> {{
    match name {{
{arms}
        _ => Err(format!("unknown def '{{}}'", name)),
    }}
}}

const SIGNATURES: &str = "[{sigs}]";

fn handle(mut s: TcpStream) {{
    let mut r = BufReader::new(s.try_clone().unwrap());
    let mut line = String::new();
    if r.read_line(&mut line).is_err() {{ return; }}
    let mut parts = line.split_whitespace();
    let (method, path) = (parts.next().unwrap_or(""), parts.next().unwrap_or("/"));
    let mut len = 0usize;
    loop {{
        let mut h = String::new();
        if r.read_line(&mut h).unwrap_or(0) == 0 || h.trim().is_empty() {{ break; }}
        if let Some(v) = h.to_ascii_lowercase().strip_prefix("content-length:") {{
            len = v.trim().parse().unwrap_or(0);
        }}
    }}
    let mut body = vec![0u8; len];
    if len > 0 {{ let _ = r.read_exact(&mut body); }}
    let body = String::from_utf8_lossy(&body).to_string();
    let name = path.trim_matches('/');
    let (code, payload) = if method == "GET" && name.is_empty() {{
        (200, SIGNATURES.to_string())
    }} else {{
        match dispatch(name, &body) {{
            Ok(v) => (200, v),
            Err(e) => (400, format!("{{{{\"error\":\"{{}}\"}}}}", e.replace('"', "'"))),
        }}
    }};
    let res = format!(
        "HTTP/1.1 {{}} OK\r\ncontent-type: application/json\r\ncontent-length: {{}}\r\n\r\n{{}}",
        code, payload.len(), payload);
    let _ = s.write_all(res.as_bytes());
}}

fn main() {{
    let port = std::env::var("PORT").unwrap_or_else(|_| "50542".into());
    let l = TcpListener::bind(format!("0.0.0.0:{{}}", port)).expect("bind");
    eprintln!("leanland rust backend on :{{}}", port);
    for s in l.incoming().flatten() {{ handle(s); }}
}}
'''


def rust_crate(defs: dict[str, Def]) -> dict[str, str]:
    return {
        'Cargo.toml': ('[package]\nname = "leanland"\nversion = "0.1.0"\nedition = "2021"\n\n'
                       '[lib]\npath = "src/lib.rs"\n\n'
                       '[[bin]]\nname = "leanland-server"\npath = "src/main.rs"\n\n'
                       '[dependencies]\n'),
        'src/lib.rs': rust(defs),
        'src/main.rs': rust_server(defs),
        'tests/examples.rs': rust_tests(defs),
        'README.md': f'# leanland — generated Rust crate\n\n{BANNER}\n\n'
                     '```\ncargo test          # the papers\' own numbers\n'
                     'cargo run --bin leanland-server\n```\n',
    }


# ---------------------------------------------------------------------------
# lean 4  (optional: only meaningful if the toolchain is installed)
# ---------------------------------------------------------------------------

LEAN_PRELUDE = '''-- {banner}
-- Real Lean 4. `lake env lean Leanland.lean` typechecks it if the toolchain is
-- installed; nothing else in leanland needs it. Float stands in for ℝ because
-- these definitions are meant to be *run*, and a noncomputable ℝ is not.
'''

_LEAN_TY = {'Real': 'Float', 'Int': 'Int', 'Nat': 'Nat', 'Bool': 'Bool',
            'Vec Real': 'Array Float', 'Vec Int': 'Array Int'}
_LEAN_OP = {'add': '+', 'sub': '-', 'mul': '*', 'div': '/', 'lt': '<', 'le': '≤',
            'gt': '>', 'ge': '≥', 'eq': '==', 'ne': '!=', 'and': '&&', 'or': '||'}


def _lean_expr(e: dict, defs: dict) -> str:
    k = e['k']
    if k == 'lit':
        return 'true' if e['v'] is True else 'false' if e['v'] is False else repr(e['v'])
    if k == 'var':
        return e['n']
    if k == 'vec':
        return '#[' + ', '.join(_lean_expr(a, defs) for a in e['a']) + ']'
    if k == 'if':
        return (f"(if {_lean_expr(e['c'], defs)} then {_lean_expr(e['t'], defs)} "
                f"else {_lean_expr(e['e'], defs)})")
    if k == 'sum':
        return (f"((List.range ({_lean_expr(e['hi'], defs)} - {_lean_expr(e['lo'], defs)} + 1))"
                f".map (fun k => let {e['i']} := {_lean_expr(e['lo'], defs)} + k; "
                f"{_lean_expr(e['b'], defs)})).foldl (· + ·) 0")
    op, a = e['op'], e['a']
    if op in _LEAN_OP:
        return f'({_lean_expr(a[0], defs)} {_LEAN_OP[op]} {_lean_expr(a[1], defs)})'
    if op == 'neg':
        return f'(-{_lean_expr(a[0], defs)})'
    if op == 'not':
        return f'(!{_lean_expr(a[0], defs)})'
    if op == 'pow':
        return f'(Float.pow {_lean_expr(a[0], defs)} {_lean_expr(a[1], defs)})'
    if op == 'idx':
        return f'({_lean_expr(a[0], defs)}[({_lean_expr(a[1], defs)}).toNat]!)'
    if op == 'len':
        return f'({_lean_expr(a[0], defs)}).size'
    if op in ('exp', 'log', 'sqrt', 'sin', 'cos', 'tanh', 'abs', 'floor', 'ceil'):
        name = {'log': 'log', 'abs': 'abs'}.get(op, op)
        return f'(Float.{name} {_lean_expr(a[0], defs)})'
    if op in ('min', 'max'):
        return f'({op} {_lean_expr(a[0], defs)} {_lean_expr(a[1], defs)})'
    return f'({op} ' + ' '.join(_lean_expr(x, defs) for x in a) + ')'


def lean4(defs: dict[str, Def]) -> str:
    out = [LEAN_PRELUDE.format(banner=BANNER)]
    for d in order(defs):
        if d.doc:
            out.append(f'/-- {d.doc} -/')
        ps = ''.join(f' ({n} : {_LEAN_TY[t]})' for n, t in d.params)
        out.append(f'def {d.name}{ps} : {_LEAN_TY[d.ret]} :=')
        for n, e in d.lets:
            out.append(f'  let {n} := {_lean_expr(e, defs)}')
        out.append(f'  {_lean_expr(d.body, defs)}')
        for c in cases(d, defs):
            args = ' '.join(repr(v) if not isinstance(v, list)
                            else '#[' + ', '.join(repr(x) for x in v) + ']' for v in c['args'])
            out.append(f'#eval {d.name} {args}   -- expected {c["expect"]!r}')
        out.append('')
    return '\n'.join(out)


# ---------------------------------------------------------------------------
# notebooks
# ---------------------------------------------------------------------------

def _cell(kind: str, src: str) -> dict:
    lines = src.splitlines(keepends=True)
    if kind == 'markdown':
        return {'cell_type': 'markdown', 'metadata': {}, 'source': lines}
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {},
            'outputs': [], 'source': lines}


def notebook(d: Def, defs: dict[str, Def], papers: dict | None = None) -> dict:
    """One def, one notebook: the claim, the citation, the lean source, the
    executable form, the paper's own numbers, and a sweep if it is 1-D.

    The notebook carries its dependencies inline rather than importing the
    generated module, so it can be handed to someone with nothing else."""
    papers = papers or {}
    needed = closure(defs, [d.name])

    cites = ''
    if d.source.get('key'):
        p = papers.get(d.source['key'], {})
        where = ', '.join(f'{k} {v}' for k, v in d.source.items() if k != 'key')
        cites = (f"\n> **Source** — {p.get('title', d.source['key'])}"
                 f"{', ' + p.get('authors', '') if p.get('authors') else ''}"
                 f"{' (' + str(p['year']) + ')' if p.get('year') else ''}"
                 f"{'. ' + where if where else ''}"
                 f"{chr(10) + '> ' + p['url'] if p.get('url') else ''}\n")

    cells = [
        _cell('markdown', f"# `{d.name}`\n\n{d.doc or ''}\n{cites}\n"
                          f"*Generated from `lib/` by leanland. The library is the source of "
                          f"truth — edit the `.lean` definition and regenerate.*"),
        _cell('markdown', '## The definition\n\n```lean\n' + (d.lean or '').strip() + '\n```'),
        _cell('code', python(needed)),
    ]
    cs = cases(d, defs)
    if cs:
        checks = ['# the numbers the source itself states', 'import math']
        for c in cs:
            args = ', '.join(repr(v) for v in c['args'])
            checks.append(f'assert math.isclose({d.name}({args}), {c["expect"]!r}, '
                          f'rel_tol=0, abs_tol={c["tol"]!r}), "{d.name}({args})"')
        checks.append(f'print("{len(cs)} example(s) from the source: ok")')
        cells.append(_cell('markdown', '## Checks against the paper'))
        cells.append(_cell('code', '\n'.join(checks)))

    reals = [i for i, (_, t) in enumerate(d.params) if t == 'Real']
    if d.ret in ('Real', 'Int') and len(d.params) == len(reals) and 1 <= len(reals) <= 2:
        base = [c['args'] for c in cs]
        base = list(base[0]) if base else [1.0] * len(d.params)
        cells.append(_cell('markdown', '## Sweep\n\nOne parameter varied, the rest held at '
                                       'the example point.'))
        cells.append(_cell('code',
                           'import numpy as np, matplotlib.pyplot as plt\n\n'
                           f'base = {base!r}\n'
                           f'names = {[n for n, _ in d.params]!r}\n'
                           'fig, axes = plt.subplots(1, len(base), figsize=(5 * len(base), 3.2),\n'
                           '                         squeeze=False)\n'
                           'for i, ax in enumerate(axes[0]):\n'
                           '    lo, hi = (base[i] - 1, base[i] + 1) if base[i] else (-1, 1)\n'
                           '    xs = np.linspace(lo, hi, 200)\n'
                           '    ys = []\n'
                           '    for x in xs:\n'
                           '        a = list(base); a[i] = float(x)\n'
                           '        try: ys.append(' + d.name + '(*a))\n'
                           '        except Exception: ys.append(float("nan"))\n'
                           '    ax.plot(xs, ys); ax.set_xlabel(names[i]); '
                           f'ax.set_ylabel("{d.name}")\n'
                           '    ax.axvline(base[i], ls=":", lw=1)\n'
                           'plt.tight_layout(); plt.show()'))

    return {'cells': cells, 'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python'},
        'leanland': {'def': d.name, 'source': d.source, 'deps': d.deps},
    }, 'nbformat': 4, 'nbformat_minor': 5}


def index_notebook(defs: dict[str, Def], papers: dict | None = None) -> dict:
    """One notebook holding the whole library, for exploring it as a unit."""
    rows = ['# leanland library', '', '| def | signature | source |', '|---|---|---|']
    for d in order(defs):
        rows.append(f"| `{d.name}` | `{d.signature()}` | {d.source.get('key', '—')} |")
    cells = [_cell('markdown', '\n'.join(rows)),
             _cell('code', python(defs)),
             _cell('code', python_tests(defs, mod='__main__').replace(
                 'from __main__ import *', '# defined above'))]
    return {'cells': cells, 'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python'}}, 'nbformat': 4, 'nbformat_minor': 5}
