"""
The agents we know how to drive — open-source agents on GitHub with a
headless command we have checked.

Each entry is everything a generated module needs (it lands verbatim in that
module's config.json under "agent"), plus what search reads. An agent found by
GitHub discovery but missing here still installs: it becomes a repo-only
module, and its owner teaches it a run command from its own page.

Placeholders in run/model/goal: {bin} the resolved binary, {query} the task,
{model} the model id, {goal} a system prompt.
"""

CATALOG = [
    {"id": "aider", "repo": "Aider-AI/aider", "label": "Aider", "icon": "Ai",
     "color": "#14b014", "kind": "coding",
     "description": "AI pair programming in your terminal; edits files in a git repo and commits with sensible messages. Works with almost any LLM.",
     "tags": ["coding", "pair-programming", "git", "refactor", "python", "cli"],
     "install": {"kind": "pip", "packages": ["aider-chat"]}, "bin": "aider",
     "run": ["{bin}", "--message", "{query}", "--yes-always", "--no-auto-commits",
             "--no-pretty", "--no-stream", "--no-check-update", "--no-show-release-notes",
             "--no-gitignore"],
     "model": ["--model", "{model}"],
     "env": ["OPENAI_API_KEY", "OPENAI_API_BASE", "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY"]},

    {"id": "mini-swe-agent", "repo": "SWE-agent/mini-swe-agent", "label": "mini-SWE-agent",
     "icon": "mS", "color": "#7c3aed", "kind": "coding",
     "description": "The 100-line software engineering agent from the SWE-agent team: bash-only, no tools, solves GitHub issues and scores well on SWE-bench.",
     "tags": ["coding", "swe-bench", "github-issues", "bash", "minimal", "python"],
     "install": {"kind": "pip", "packages": ["mini-swe-agent"]}, "bin": "mini",
     "run": ["{bin}", "--yolo", "--exit-immediately", "--task", "{query}"],
     "model": ["--model", "{model}"],
     "env": ["MSWEA_MODEL_NAME", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY"]},

    {"id": "smolagents", "repo": "huggingface/smolagents", "label": "smolagents",
     "icon": "sm", "color": "#ffcc4d", "kind": "general",
     "description": "Hugging Face's barebones library for agents that think in code: a CodeAgent writes Python actions; runs with local or hosted models.",
     "tags": ["general", "code-agent", "huggingface", "python", "web-search", "framework"],
     "install": {"kind": "pip", "packages": ["smolagents[toolkit]"]}, "bin": "smolagent",
     "run": ["{bin}", "{query}"],
     "model": ["--model-id", "{model}"],
     "env": ["HF_TOKEN", "OPENAI_API_KEY", "OPENAI_API_BASE"]},

    {"id": "open-interpreter", "repo": "openinterpreter/openinterpreter",
     "label": "Open Interpreter", "icon": "OI", "color": "#e5e7eb", "kind": "general",
     "description": "A natural-language interface to your computer: lets an LLM run Python, JavaScript and shell code locally to do what you ask.",
     "tags": ["general", "code-execution", "shell", "local", "python", "automation"],
     "install": {"kind": "pip", "packages": ["open-interpreter"]}, "bin": "interpreter",
     "run": ["{bin}", "--auto_run", "--plain", "--no-llm_supports_functions", "-e", "{query}"],
     "model": ["--model", "{model}"],
     "env": ["OPENAI_API_KEY", "OPENAI_API_BASE", "ANTHROPIC_API_KEY"]},

    {"id": "goose", "repo": "aaif-goose/goose", "label": "goose", "icon": "go",
     "color": "#f97316", "kind": "coding",
     "description": "An open, extensible on-machine AI agent from Block: installs, runs, edits and tests code with any LLM and MCP extensions.",
     "tags": ["coding", "mcp", "extensions", "local", "rust", "automation"],
     "install": {"kind": "script",
                 "command": "curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash"},
     "bin": "goose",
     "run": ["{bin}", "run", "--no-session", "-t", "{query}"],
     "env": ["GOOSE_PROVIDER", "GOOSE_MODEL", "OPENAI_API_KEY", "OPENAI_HOST", "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY"]},

    {"id": "opencode", "repo": "anomalyco/opencode", "label": "opencode", "icon": "oc",
     "color": "#94a3b8", "kind": "coding",
     "description": "The open-source AI coding agent built for the terminal; provider-agnostic, with LSP integration and a client/server design.",
     "tags": ["coding", "terminal", "tui", "lsp", "typescript", "provider-agnostic"],
     "install": {"kind": "npm", "packages": ["opencode-ai"]}, "bin": "opencode",
     "run": ["{bin}", "run", "{query}"],
     "model": ["--model", "{model}"],
     "env": ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY"]},

    {"id": "crush", "repo": "charmbracelet/crush", "label": "Crush", "icon": "Cr",
     "color": "#ff5fd2", "kind": "coding",
     "description": "Charm's glamorous agentic coding CLI: multi-model, session-based, LSP-aware and extensible with MCP.",
     "tags": ["coding", "terminal", "go", "mcp", "lsp"],
     "install": {"kind": "npm", "packages": ["@charmland/crush"]}, "bin": "crush",
     "run": ["{bin}", "run", "--yolo", "{query}"],
     "env": ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY"]},

    {"id": "gemini-cli", "repo": "google-gemini/gemini-cli", "label": "Gemini CLI",
     "icon": "Ge", "color": "#4285f4", "kind": "coding",
     "description": "Google's open-source agent that brings Gemini into the terminal: reads and edits code, runs commands, searches the web.",
     "tags": ["coding", "terminal", "gemini", "google", "mcp", "typescript"],
     "install": {"kind": "npm", "packages": ["@google/gemini-cli"]}, "bin": "gemini",
     "run": ["{bin}", "--yolo", "-p", "{query}"],
     "model": ["-m", "{model}"],
     "env": ["GEMINI_API_KEY", "GOOGLE_API_KEY"]},

    {"id": "qwen-code", "repo": "QwenLM/qwen-code", "label": "Qwen Code", "icon": "Qw",
     "color": "#615ced", "kind": "coding",
     "description": "A command-line coding agent tuned for Qwen3-Coder models; a Gemini CLI fork that talks to any OpenAI-compatible endpoint.",
     "tags": ["coding", "terminal", "qwen", "openai-compatible", "local-models"],
     "install": {"kind": "npm", "packages": ["@qwen-code/qwen-code"]}, "bin": "qwen",
     "run": ["{bin}", "--yolo", "-p", "{query}"],
     "model": ["-m", "{model}"],
     "env": ["OPENAI_API_KEY", "OPENAI_BASE_URL", "OPENAI_MODEL"]},

    {"id": "continue-cli", "repo": "continuedev/continue", "label": "Continue CLI",
     "icon": "Co", "color": "#22d3ee", "kind": "coding",
     "description": "Continue's open-source coding agent as a CLI (cn): headless mode for scripts and CI, configurable models and rules.",
     "tags": ["coding", "ci", "headless", "terminal", "typescript"],
     "install": {"kind": "npm", "packages": ["@continuedev/cli"]}, "bin": "cn",
     "run": ["{bin}", "-p", "{query}"],
     "env": ["CONTINUE_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"]},

    # well-known agents with no stable one-shot CLI: listed so search finds
    # them, installed as repo-only modules the owner finishes by hand
    {"id": "openhands", "repo": "OpenHands/OpenHands", "label": "OpenHands",
     "icon": "OH", "color": "#facc15", "kind": "coding",
     "description": "Platform for software development agents (formerly OpenDevin): agents that modify code, run commands, browse the web and call APIs, usually inside a Docker sandbox.",
     "tags": ["coding", "docker", "sandbox", "web-browsing", "swe-bench", "platform"],
     "install": {"kind": "pip", "packages": ["openhands-ai"]}, "bin": "openhands",
     "env": ["LLM_API_KEY", "LLM_MODEL", "LLM_BASE_URL"]},
    {"id": "swe-agent", "repo": "SWE-agent/SWE-agent", "label": "SWE-agent",
     "icon": "SW", "color": "#6366f1", "kind": "coding",
     "description": "Takes a GitHub issue and tries to fix it automatically with your LM of choice; also used for offensive cybersecurity and competitive coding.",
     "tags": ["coding", "github-issues", "swe-bench", "research", "python"],
     "install": {"kind": "git"}, "env": ["OPENAI_API_KEY", "ANTHROPIC_API_KEY"]},
    {"id": "hermes-agent", "repo": "NousResearch/hermes-agent", "label": "Hermes Agent",
     "icon": "He", "color": "#8b5cf6", "kind": "general",
     "description": "Nous Research's self-improving agent with persistent memory, skills it writes for itself and tool use across terminal, messaging and the web.",
     "tags": ["general", "memory", "skills", "self-improving", "nous"],
     "install": {"kind": "git"}, "env": ["OPENROUTER_API_KEY", "OPENAI_API_KEY"]},
    {"id": "gpt-engineer", "repo": "AntonOsika/gpt-engineer", "label": "gpt-engineer",
     "icon": "gE", "color": "#10b981", "kind": "coding",
     "description": "Specify what you want built in natural language and the AI writes and executes the code; the original codebase-generation CLI.",
     "tags": ["coding", "codegen", "scaffold", "python"],
     "install": {"kind": "pip", "packages": ["gpt-engineer"]}, "bin": "gpte",
     "env": ["OPENAI_API_KEY", "OPENAI_API_BASE"]},
    {"id": "autogpt", "repo": "Significant-Gravitas/AutoGPT", "label": "AutoGPT",
     "icon": "AG", "color": "#0ea5e9", "kind": "platform",
     "description": "Platform for building, deploying and running continuous AI agents that automate complex workflows.",
     "tags": ["platform", "autonomous", "workflows", "low-code"],
     "install": {"kind": "git"}, "env": ["OPENAI_API_KEY"]},
    {"id": "openmanus", "repo": "FoundationAgents/OpenManus", "label": "OpenManus",
     "icon": "OM", "color": "#f43f5e", "kind": "general",
     "description": "Open-source general agent in the style of Manus: plans, browses, runs Python and edits files toward a goal.",
     "tags": ["general", "browser", "planning", "python"],
     "install": {"kind": "git"}, "env": ["OPENAI_API_KEY"]},
    {"id": "browser-use", "repo": "browser-use/browser-use", "label": "Browser Use",
     "icon": "BU", "color": "#ff7a00", "kind": "browser",
     "description": "Make websites accessible to AI agents: drives a real browser to complete online tasks from a natural-language instruction.",
     "tags": ["browser", "web-automation", "playwright", "python"],
     "install": {"kind": "pip", "packages": ["browser-use"]}, "env": ["OPENAI_API_KEY", "ANTHROPIC_API_KEY"]},
    {"id": "metagpt", "repo": "FoundationAgents/MetaGPT", "label": "MetaGPT",
     "icon": "MG", "color": "#2563eb", "kind": "multi-agent",
     "description": "Multi-agent framework that gives LLMs software-company roles (PM, architect, engineer) to go from a one-line requirement to a repo.",
     "tags": ["multi-agent", "software-company", "codegen", "python"],
     "install": {"kind": "pip", "packages": ["metagpt"]}, "bin": "metagpt",
     "env": ["OPENAI_API_KEY"]},
    {"id": "crewai", "repo": "crewAIInc/crewAI", "label": "CrewAI", "icon": "Cw",
     "color": "#ef4444", "kind": "framework",
     "description": "Framework for orchestrating role-playing autonomous agents that collaborate as a crew on complex tasks.",
     "tags": ["framework", "multi-agent", "orchestration", "python"],
     "install": {"kind": "git"}, "env": ["OPENAI_API_KEY"]},
    {"id": "autogen", "repo": "microsoft/autogen", "label": "AutoGen", "icon": "Au",
     "color": "#0078d4", "kind": "framework",
     "description": "Microsoft's programming framework for agentic AI: multi-agent conversations, tools and human-in-the-loop.",
     "tags": ["framework", "multi-agent", "microsoft", "python"],
     "install": {"kind": "git"}, "env": ["OPENAI_API_KEY"]},
    {"id": "langgraph", "repo": "langchain-ai/langgraph", "label": "LangGraph", "icon": "LG",
     "color": "#1c3c3c", "kind": "framework",
     "description": "Build resilient language agents as graphs: low-level orchestration with persistence, streaming and human-in-the-loop.",
     "tags": ["framework", "graph", "orchestration", "langchain", "python"],
     "install": {"kind": "git"}, "env": ["OPENAI_API_KEY"]},
]

# the two CLIs this module already drives through dedicated runner modules —
# listed so search finds them, never scaffolded twice
NATIVE = [
    {"id": "claude-code", "repo": "anthropics/claude-code", "label": "Claude Code",
     "kind": "coding", "native": "claudecode", "harness": "claude",
     "description": "Anthropic's agentic coding tool in the terminal. Already a harness here (orbit/claudecode).",
     "tags": ["coding", "terminal", "anthropic", "claude", "mcp"]},
    {"id": "codex", "repo": "openai/codex", "label": "Codex CLI", "kind": "coding",
     "native": "codexcli", "harness": "codex",
     "description": "OpenAI's lightweight coding agent that runs in your terminal. Already a harness here (orbit/codexcli).",
     "tags": ["coding", "terminal", "openai", "rust"]},
]
