"""subnets — one mod per Bittensor subnet, regenerated once a day.

`sync()` reads the local orbit/bt index (screener + news + trade tape — no
third-party API, no keys) and writes, for every live netuid:

    subnets/sn<N>/config.json   identity, links, market numbers, related mods
    subnets/sn<N>/README.md     human page: what it is, market, 24h flow, news
    subnets/sn<N>/data.json     the full daily snapshot (what the mod serves offline)
    subnets/sn<N>/mod.py        a 10-line shim over base.Subnet — written ONCE;
                                if you replace it (drop the GENERATED marker) it
                                is never overwritten again.

Netuids that disappear are kept and marked `active: false`; a re-registered
netuid (new owner) records the old identity under `previous`. Every write is
atomic and skipped when nothing changed apart from the timestamp.

CLI (what the cron runs):  python3 mod.py sync | status | install_cron | uninstall_cron
"""

import fcntl
import json
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from base import bt_call  # noqa: E402

ORBIT = os.path.dirname(HERE)
STATE = os.path.expanduser(os.environ.get('SUBNETS_STATE', '~/.mod/subnets'))
LOCK = os.path.join(STATE, 'sync.lock')
LOG = '/tmp/subnets-daily.log'
CRON_TAG = '# subnets daily mod sync'
CRON_SCHEDULE = os.environ.get('SUBNETS_CRON', '41 5 * * *')   # 05:41 UTC, after bt's day roll
GENERATED = '# GENERATED by orbit/subnets'
NEWS_PER_MOD = 8


def _now():
    return int(time.time())


def _day(ts):
    return time.strftime('%Y-%m-%d', time.gmtime(ts))


def _write(path, text):
    """Atomic write; returns True when the file actually changed."""
    try:
        with open(path) as f:
            if f.read() == text:
                return False
    except OSError:
        pass
    tmp = f'{path}.tmp{os.getpid()}'
    with open(tmp, 'w') as f:
        f.write(text)
    os.replace(tmp, path)
    return True


def _read_json(path, default=None):
    try:
        with open(path) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return default


def _dumps(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=False) + '\n'


def _strip_volatile(obj):
    """Compare snapshots without the timestamps that change every run."""
    if isinstance(obj, dict):
        return {k: _strip_volatile(v) for k, v in obj.items() if k not in ('updated', 'updated_day', 'block')}
    return obj


def _num(x, digits=4):
    if x is None:
        return '—'
    if abs(x) >= 1000:
        return f'{x:,.0f}'
    return f'{x:,.{digits}f}'


def _pct(x):
    return '—' if x is None else f'{x:+.2f}%'


def _md(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ').strip()


def related_mods(rows, orbit=ORBIT):
    """Hand-built fleet mods that cover a subnet: a `netuid` field in their
    config.json, or an orbit dir named exactly like the subnet (chutes, targon…)."""
    names = {}
    for r in rows:
        key = re.sub(r'[^a-z0-9]', '', (r.get('name') or '').lower().split('.')[0])
        if len(key) >= 4:
            names.setdefault(key, r['netuid'])
    out = {}
    for d in sorted(os.listdir(orbit)):
        if d == 'subnets':
            continue
        cfg = _read_json(os.path.join(orbit, d, 'config.json'))
        if not isinstance(cfg, dict):
            continue
        n = cfg.get('netuid')
        if isinstance(n, int):
            out.setdefault(n, []).append(d)
        elif d in names:
            out.setdefault(names[d], []).append(d)
    return {k: sorted(set(v)) for k, v in out.items()}


# ---------------------------------------------------------------- rendering

def class_name(netuid):
    return f'Sn{netuid}'


def render_mod_py(netuid, name):
    return f'''{GENERATED} — delete this line to own the file; sync then leaves it alone.
"""sn{netuid} — {name or 'subnet ' + str(netuid)} (Bittensor netuid {netuid}).

Fns: info, price, news, trades, daily, history, validators, neurons, links,
snapshot, readme, refresh. Live from the local orbit/bt index, snapshot fallback.
"""
import importlib.util as _u, os as _os
_here = _os.path.dirname(_os.path.abspath(__file__))
_s = _u.spec_from_file_location('_subnets_base', _os.path.join(_os.path.dirname(_here), 'base.py'))
_b = _u.module_from_spec(_s); _s.loader.exec_module(_b)


class Mod(_b.Subnet):
    netuid = {netuid}
    dirpath = _here
'''


def render_readme(d):
    m, t = d['market'], d.get('trades_24h') or {}
    lines = [f"# sn{d['netuid']} — {d['name'] or 'unnamed'} {d.get('symbol') or ''}".rstrip(), '']
    if not d.get('active', True):
        lines += [f"> **Inactive** — netuid {d['netuid']} was not in the live screener on "
                  f"{d.get('inactive_since_day', d['updated_day'])}. Kept for history.", '']
    if d.get('description'):
        lines += [d['description'], '']
    lines += [f"Bittensor subnet **{d['netuid']}** · generated daily by `orbit/subnets` from the "
              f"local `orbit/bt` index · updated {d['updated_day']} (block {d.get('block') or '—'}).", '']
    links = [(k, d.get(k)) for k in ('github', 'url', 'discord')]
    links = [f'[{k}]({v if str(v).startswith("http") else "https://" + v})'
             if k != 'discord' or str(v).startswith('http') else f'discord `{v}`' for k, v in links if v]
    if links:
        lines += ['Links: ' + ' · '.join(links), '']
    if d.get('related'):
        lines += ['Fleet mods for this subnet: ' + ', '.join(f'`{r}`' for r in d['related']), '']
    lines += ['## Market', '', '| price (τ) | 1h | 24h | 7d | mcap (τ) | pool τ | 24h vol (τ) |',
              '|---|---|---|---|---|---|---|',
              f"| {_num(m.get('price'), 6)} | {_pct(m.get('change_1h'))} | {_pct(m.get('change_24h'))} | "
              f"{_pct(m.get('change_7d'))} | {_num(m.get('market_cap'))} | {_num(m.get('tao_in'))} | "
              f"{_num(m.get('vol_24h'), 2)} |", '']
    if t.get('trades'):
        lines += ['## Last 24h flow', '',
                  f"{t['trades']} trades by {t.get('traders', '—')} coldkeys · "
                  f"{t.get('buys', 0)} buys ({_num(t.get('buy_tao'), 2)} τ) / "
                  f"{t.get('sells', 0)} sells ({_num(t.get('sell_tao'), 2)} τ) · "
                  f"net {_num(t.get('net_tao'), 2)} τ", '']
    if d.get('news'):
        lines += ['## News', '']
        for n in d['news']:
            title_part = (f"[{_md(n.get('title'))}]({n.get('url')})"
                          if n.get('url') else _md(n.get('title')))
            lines.append(f"- {_day(n['ts']) if n.get('ts') else ''} · {n.get('kind', '')} · "
                         f"{title_part} — {_md(n.get('publisher'))}")
        lines.append('')
    lines += ['## Use', '', '```bash',
              f"m subnets.sn{d['netuid']}/info        # live identity + market (snapshot if bt is down)",
              f"m subnets.sn{d['netuid']}/news        # scraped news",
              f"m subnets.sn{d['netuid']}/trades      # 24h alpha tape",
              f"m subnets.sn{d['netuid']}/daily       # daily candles",
              f"python3 orbit/subnets/sn{d['netuid']}/mod.py  # or import it: Mod().info()",
              '```', '',
              '_config.json, README.md and data.json are regenerated every day — '
              'put hand-written code in a new file next to mod.py._', '']
    return '\n'.join(lines)


def build_snapshot(row, trades, news, related, block, ts):
    return {
        'netuid': row['netuid'],
        'name': row.get('name'),
        'symbol': row.get('symbol'),
        'owner': row.get('owner'),
        'description': row.get('description'),
        'github': row.get('github'),
        'url': row.get('url'),
        'discord': row.get('discord'),
        'logo': row.get('logo'),
        'registered_at': row.get('registered_at'),
        'tempo': row.get('tempo'),
        'active': True,
        'block': block,
        'related': related,
        'market': {k: row.get(k) for k in ('price', 'moving_price', 'market_cap', 'tao_in', 'alpha_in',
                                           'alpha_out', 'volume', 'vol_24h', 'emission',
                                           'change_1h', 'change_24h', 'change_7d')},
        'spark_24h': row.get('spark') or [],
        'trades_24h': (trades or {}).get('summary'),
        'top_traders_24h': ((trades or {}).get('top') or [])[:5],
        'news': [{k: n.get(k) for k in ('ts', 'kind', 'source', 'title', 'url', 'publisher')}
                 for n in (news or {}).get('items', [])][:NEWS_PER_MOD],
        'updated': ts,
        'updated_day': _day(ts),
    }


def build_config(snap, prev_cfg):
    n = snap['netuid']
    desc = (snap.get('description') or 'Bittensor subnet').strip().rstrip('.')
    cfg = {
        'name': f'sn{n}',
        'version': '1.0.0',
        'description': f"SN{n} {snap.get('name') or ''} — {desc}. Daily snapshot + live reads "
                       f"(price, news, trades, candles, validators) from the local bt index.",
        'icon': snap.get('symbol') or 'τ',
        'chain': 'bittensor',
        'netuid': n,
        'subnet': snap.get('name'),
        'symbol': snap.get('symbol'),
        'owner': snap.get('owner'),
        'github': snap.get('github'),
        'url': snap.get('url'),
        'discord': snap.get('discord'),
        'logo': snap.get('logo'),
        'related': snap.get('related') or [],
        'active': snap.get('active', True),
        'route': False,
        'generated_by': 'subnets',
        'updated': snap.get('updated_day'),
        'urls': {'bt': f'/bt/markets?sn={n}', 'news': f'/bt/news?netuid={n}'},
        'fns': ['info', 'price', 'news', 'trades', 'daily', 'history', 'validators',
                'neurons', 'links', 'snapshot', 'readme', 'refresh'],
    }
    prev = list((prev_cfg or {}).get('previous') or [])
    if prev_cfg and prev_cfg.get('owner') and snap.get('owner') and prev_cfg['owner'] != snap['owner']:
        prev.insert(0, {k: prev_cfg.get(k) for k in ('subnet', 'owner', 'github', 'url', 'updated')})
    if prev:
        cfg['previous'] = prev[:10]
    for k in ('schema',):                 # keep fields other tools stamp on
        if prev_cfg and k in prev_cfg:
            cfg[k] = prev_cfg[k]
    return cfg


# ---------------------------------------------------------------- the mod

class Mod:
    description = 'One mod per Bittensor subnet (subnets/sn<N>), regenerated daily from orbit/bt.'

    def __init__(self, root=HERE):
        self.root = root

    def dir(self, netuid):
        return os.path.join(self.root, f'sn{int(netuid)}')

    def ls(self):
        """Every generated subnet mod: netuid, name, active, last update."""
        out = []
        for d in os.listdir(self.root):
            m = re.fullmatch(r'sn(\d+)', d)
            cfg = m and _read_json(os.path.join(self.root, d, 'config.json'))
            if cfg:
                out.append({'mod': f'subnets.{d}', 'netuid': int(m.group(1)), 'name': cfg.get('subnet'),
                            'active': cfg.get('active', True), 'updated': cfg.get('updated'),
                            'related': cfg.get('related') or []})
        return sorted(out, key=lambda r: r['netuid'])

    def get(self, netuid):
        """One subnet's daily snapshot."""
        return _read_json(os.path.join(self.dir(netuid), 'data.json'), {'error': f'no sn{netuid}'})

    def status(self):
        last = _read_json(os.path.join(STATE, 'last_sync.json'), {})
        mods = self.ls()
        return {'mods': len(mods), 'active': sum(m['active'] for m in mods),
                'last_sync': last, 'cron': self.cron_line() in _crontab(), 'schedule': CRON_SCHEDULE}

    def sync(self, netuids=None, news=True, trades=True, verbose=True):
        """Regenerate subnet mods from the bt index. netuids=None → all of them."""
        os.makedirs(STATE, exist_ok=True)
        with open(LOCK, 'w') as lk:
            try:
                fcntl.flock(lk, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                return {'ok': False, 'error': 'another sync is running'}
            return self._sync(netuids, news, trades, verbose)

    def _sync(self, netuids, news, trades, verbose):
        t0, ts = time.time(), _now()
        scr = bt_call('bt_screener', limit=1000)
        rows = scr['rows']
        if not rows:
            raise RuntimeError('bt screener returned no subnets — refusing to mark everything inactive')
        live = {r['netuid'] for r in rows}
        related = related_mods(rows)
        want = set(int(n) for n in netuids) if netuids is not None else None
        stats = {'written': 0, 'unchanged': 0, 'new': 0, 'inactive': 0, 'errors': []}

        for row in rows:
            n = row['netuid']
            if want is not None and n not in want:
                continue
            tr = nw = None
            if trades and n != 0:
                try:
                    tr = bt_call('bt_trades', netuid=n, hours=24, limit=1, timeout=120)
                except Exception as e:
                    stats['errors'].append(f'sn{n} trades: {e}')
            if news:
                try:
                    nw = bt_call('bt_news', netuid=n, limit=NEWS_PER_MOD, days=30)
                except Exception as e:
                    stats['errors'].append(f'sn{n} news: {e}')
            snap = build_snapshot(row, tr, nw, related.get(n, []), scr.get('block'), ts)
            self._emit(snap, stats)
            if verbose:
                print(f"sn{n:<4} {row.get('name') or '':24} ok", flush=True)

        # netuids we have a mod for that the chain no longer lists
        for d in os.listdir(self.root):
            m = re.fullmatch(r'sn(\d+)', d)
            if not m or int(m.group(1)) in live or (want is not None and int(m.group(1)) not in want):
                continue
            snap = _read_json(os.path.join(self.root, d, 'data.json'))
            if snap and snap.get('active', True):
                snap.update(active=False, inactive_since_day=_day(ts), updated=ts, updated_day=_day(ts))
                self._emit(snap, stats)
                stats['inactive'] += 1

        result = {'ok': True, 'at': ts, 'day': _day(ts), 'subnets': len(rows),
                  'secs': round(time.time() - t0, 1), **stats}
        if want is None:
            _write(os.path.join(STATE, 'last_sync.json'), _dumps(result))
        return result

    def _emit(self, snap, stats):
        d = self.dir(snap['netuid'])
        fresh = not os.path.isdir(d)
        os.makedirs(d, exist_ok=True)
        old = _read_json(os.path.join(d, 'data.json'))
        if old and _strip_volatile(old) == _strip_volatile(snap):
            stats['unchanged'] += 1
            return
        prev_cfg = _read_json(os.path.join(d, 'config.json'))
        _write(os.path.join(d, 'data.json'), _dumps(snap))
        _write(os.path.join(d, 'config.json'), _dumps(build_config(snap, prev_cfg)))
        _write(os.path.join(d, 'README.md'), render_readme(snap))
        mp = os.path.join(d, 'mod.py')
        try:
            owned = not open(mp).read().startswith(GENERATED)
        except OSError:
            owned = False
        if not owned:
            _write(mp, render_mod_py(snap['netuid'], snap.get('name')))
        stats['new' if fresh else 'written'] += 1

    # -- cron ---------------------------------------------------------------
    def cron_line(self):
        py = sys.executable or '/usr/bin/python3'
        return (f'{CRON_SCHEDULE} cd {HERE} && {py} {os.path.join(HERE, "mod.py")} sync '
                f'>> {LOG} 2>&1  {CRON_TAG}')

    def install_cron(self):
        """Add (or replace) the daily sync line in the user's crontab. Idempotent."""
        lines = [l for l in _crontab().splitlines() if CRON_TAG not in l]
        lines.append(self.cron_line())
        subprocess.run(['crontab', '-'], input='\n'.join(lines) + '\n', text=True, check=True)
        return {'ok': True, 'line': self.cron_line()}

    def uninstall_cron(self):
        lines = [l for l in _crontab().splitlines() if CRON_TAG not in l]
        subprocess.run(['crontab', '-'], input='\n'.join(lines) + '\n', text=True, check=True)
        return {'ok': True}


def _crontab():
    r = subprocess.run(['crontab', '-l'], capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ''


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'status'
    args = [int(a) for a in sys.argv[2:]] or None
    mod = Mod()
    if cmd == 'sync':
        print(time.strftime('%F %T'), 'subnets sync start', flush=True)
        try:
            out = mod.sync(netuids=args)
        except Exception as e:                       # bt down: keep yesterday's mods
            print(json.dumps({'ok': False, 'error': str(e)}), flush=True)
            sys.exit(1)
        print(json.dumps({k: v for k, v in out.items() if k != 'errors'} |
                         {'errors': len(out.get('errors', []))}), flush=True)
        for e in out.get('errors', [])[:20]:
            print('  !', e)
    else:
        print(json.dumps(getattr(mod, cmd)(), indent=2))
