import type { Config } from 'tailwindcss'

/* Every colour in the app runs through a CSS variable so a theme is one block
 * of tokens (globals.css, generated by scripts/gen_theme_tokens.py) rather
 * than a sweep through 8k lines of JSX. The palette names below are the ones
 * the components already use — emerald is "the accent", gray is the text
 * ramp, white is "ink" — so switching themes needs no markup change.
 * Everything keeps <alpha-value>, so `bg-emerald-500/15` still tints. */
const rgb = (v: string) => `rgb(var(${v}) / <alpha-value>)`
const scale = (v: string, stops: number[]) =>
  Object.fromEntries(stops.map(s => [s, rgb(`${v}-${s}`)]))

const accent = scale('--a', [200, 300, 400, 500, 600])
const warn = scale('--w', [200, 300, 400, 500])
const info = scale('--i', [200, 300, 400, 500, 600])
const alt = scale('--v', [200, 300, 400, 500])
const danger = scale('--d', [200, 300, 400, 500])
const gray = scale('--g', [100, 200, 300, 400, 500, 600, 700, 800])

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // ink: the "bright" end of the theme — dark ink on light themes, so
        // text-white, bg-white/5 and border-white/10 all invert for free.
        white: rgb('--ink'),
        surface: { 0: rgb('--s-0'), 1: rgb('--s-1'), 2: rgb('--s-2') },
        emerald: accent,
        gray: { ...gray, 900: rgb('--g-800') },
        slate: gray,
        amber: warn,
        yellow: warn,
        orange: warn,
        sky: info,
        cyan: info,
        blue: info,
        violet: alt,
        purple: alt,
        fuchsia: alt,
        pink: alt,
        red: danger,
        rose: danger,
        green: accent,
      },
    },
  },
  plugins: [],
}
export default config
