# GENERATED by orbit/subnets — delete this line to own the file; sync then leaves it alone.
"""sn127 — Astrid (Bittensor netuid 127).

Fns: info, price, news, trades, daily, history, validators, neurons, links,
snapshot, readme, refresh. Live from the local orbit/bt index, snapshot fallback.
"""
import importlib.util as _u, os as _os
_here = _os.path.dirname(_os.path.abspath(__file__))
_s = _u.spec_from_file_location('_subnets_base', _os.path.join(_os.path.dirname(_here), 'base.py'))
_b = _u.module_from_spec(_s); _s.loader.exec_module(_b)


class Mod(_b.Subnet):
    netuid = 127
    dirpath = _here
